### ISSUE TITLE
Find 2 HPCDs and install them

### ISSUE THREAD

**Issue by gw-vis** [gw-vis/ITMY#3]
### Todo
- [x] Find 2 HPCDs and install them
[Note] 1 HPCD might be missing. Another HPCD: Ask TM

**Comment by YoshinoriFujii** [comment]
I grabbed 2 coil drivers from cryo-payload, which was used for actuating IM-stage from:
  - ETMX
  - ITMX  

references: 
[klog#7106](http://klog.icrr.u-tokyo.ac.jp/osl/?r=7106  "klog#7106")  
[klog#7096](http://klog.icrr.u-tokyo.ac.jp/osl/?r=7096  "klog#7096")
